export const questionsData = {
  "Artificial Intelligence": {
    partA: [
      "Characterize the environment of an agent playing soccer.",
      "Some people like every vegetable. Convert it to First order Logic.",
      "Justify the purpose of Bayesian networks.",
      "What is Causal networks?",
      "Can an agent that senses only partial information about the state always be perfectly rational?",
      "Define admissible and dominant heuristics.",
      "What are the three levels in describing knowledge based agent?",
      "State Unification in first order logic.",
      "Why does uncertainty arise?",
      "What is Baye's rule? Mention its use.",
      "What is the purpose of a contingency plan?",
      "For each environment determine the most appropriate agent architecture: (a) Medical Diagnosis System (b) Satellite Image Analysis System (c) Part Picking Robot (d) Interactive English Tutor",
      "Formulate PEAS for an automated taxi driver.",
      "Compare and Contrast Admissible and Consistent Heuristics.",
      "Comment on the statement 'Breadth-first search is a special case of uniform-cost search'.",
      "Class scheduling formulation (professors, classrooms, classes, time slots).",
      "Define AI and write the applications of AI.",
      "List the steps involved in simple problem solving technique.",
      "What is Heuristic function?",
      "What are the things that agent knows in online search problems?",
      "Write the components of a game.",
      "What do you mean by constraint propagation?",
      "Why cannot we use traditional minimax for games with chance (e.g., backgammon)?",
      "Unicorn resolution proof problem (prove: the unicorn is horned).",
      "CSP precise formulation (variables, domain, constraints) for professors/classrooms/classes/time slots.",
      "State the converse and contrapositive of: 'When I stay up late, it is necessary that I sleep until noon'.",
      "Define the terms belief state and state estimation.",
      "How are Bayesian networks represented?"
    ],
    partB: [
      "Elaborate on the need for Local search algorithms and discuss any one algorithm in detail.",
      "Discuss on Online Search Agents that uses depth-first exploration.",
      "Brief on MinMax algorithm and discuss the need for alpha beta pruning.",
      "Formulate the Map-coloring problem as CSP and explain with an example.",
      "Define the properties of an environment. Give PEAS description table for agents such as an automated taxi driver, ATM system, Medical diagnosis system.",
      "Demonstrate any two uninformed search strategies in detail.",
      "Explain the architecture of agent.",
      "What is Bayesian Network? How Bayesian network is used to represent knowledge in uncertain domain.",
      "Explain the method of performing exact inference.",
      "What is an Agent? How does it interact with environment? Explain.",
      "What are informed search techniques? Explain any one.",
      "List the basic kinds of intelligent agents and explain any two agents with neat schematic diagram.",
      "What is heuristic search technique in AI? How does heuristics search work? Explain its advantages and disadvantages.",
      "Describe the local search algorithm with neat sketch.",
      "Explain the steps involved in formulating problems with example.",
      "Write short notes on genetic algorithm.",
      "Explain the constraint satisfaction problem and the variations on CSP with example.",
      "Write short notes on Monte-Carlo search.",
      "Define local consistency. What are the different types? Explain any two.",
      "What are logical connectives? Explain in detail.",
      "Describe an algorithm for general propositional inference based on model checking.",
      "Discuss the Knowledge Engineering Process with illustration. Depict forward chaining.",
      "What is Bayesian network? Explain constructing Bayesian networks.",
      "What are the ways to understand the semantics of Bayesian Networks?",
      "Discuss the exact inference in Bayesian networks.",
      "How does Alpha beta search differ from Minimax? Analyse.",
      "What is the significance of knowledge representation? Mention desirable properties.",
      "What is conjunctive normal form? Convert sentences to CNF with example. Depict real-time applications.",
      "Explain the method of performing approximate inference.",
      "Explain in detail about causal network.",
      "Define uncertain knowledge, prior probability and conditional probability. State Bayes theorem. How is it useful for decision making under uncertainty. Explain belief network briefly.",
      "How to represent knowledge in an uncertain domain.",
      "What is an intelligent agent? Explain percept, percept sequence, agent function and agent program with vacuum cleaner example.",
      "Explain the components necessary to define a problem.",
      "What is the difference between informed and uninformed search strategy?",
      "Explain in detail the structure of intelligent agents."
    ],
    important: [
      "Explain the architecture of an intelligent agent with its components and functions.",
      "Discuss PEAS description and its importance in agent design with examples.",
      "Explain different types of environments: fully/partially observable, deterministic/stochastic.",
      "Describe uninformed search strategies: BFS, DFS, Uniform Cost Search with complexity analysis.",
      "Explain informed search techniques: Greedy Best-First and A* algorithm with heuristics.",
      "What is heuristic function? Explain admissible and consistent heuristics.",
      "Explain the Minimax algorithm and Alpha-Beta pruning for game playing.",
      "Discuss local search algorithms: Hill Climbing, Simulated Annealing, Genetic Algorithms.",
      "Explain Constraint Satisfaction Problems (CSP) and constraint propagation techniques.",
      "What is knowledge representation? Explain propositional and first-order logic.",
      "Describe first-order logic: syntax, semantics, unification, and resolution.",
      "Explain Bayesian Networks: structure, conditional independence, and inference.",
      "Discuss probability theory: prior probability, conditional probability, Bayes theorem.",
      "Explain exact inference in Bayesian Networks: enumeration, variable elimination.",
      "Describe approximate inference: Markov Chain Monte Carlo, Particle Filtering.",
      "Explain planning in AI: problem formulation, state space search, planning graphs.",
      "What is natural language processing? Explain parsing and semantic analysis.",
      "Describe machine learning approaches in AI systems.",
      "Explain philosophical aspects: Turing Test, Chinese Room argument.",
      "Discuss ethical considerations and future directions in AI."
    ]
  },
  "Machine Learning": {
    partA: [
      "Define Machine Learning.",
      "List any two applications of Machine Learning.",
      "What is hypothesis space?",
      "Define inductive bias.",
      "What is generalization?",
      "Define bias–variance trade-off.",
      "What is VC dimension?",
      "What is PAC learning?",
      "Define linear regression.",
      "What is least squares method?",
      "What is gradient descent?",
      "Difference between single and multiple linear regression?",
      "Define logistic regression.",
      "What is perceptron model?",
      "Define discriminant function.",
      "What is Naive Bayes classifier?",
      "Define Support Vector Machine (SVM).",
      "What is margin in SVM?",
      "What is decision tree?",
      "Define Random Forest.",
      "What is ensemble learning?",
      "Define bagging.",
      "Define boosting.",
      "What is stacking?",
      "What is K-means clustering?",
      "Define KNN algorithm.",
      "What is instance-based learning?",
      "Define Gaussian Mixture Model (GMM).",
      "What is Expectation Maximization (EM)?",
      "What is Multilayer Perceptron (MLP)?",
      "Define activation function.",
      "What is backpropagation?",
      "What is vanishing gradient problem?",
      "What is dropout in neural networks?",
      "Define cross-validation."
    ],
    partB: [
      "Explain the importance of Linear Algebra in Machine Learning.",
      "Describe the motivation and real-world applications of Machine Learning.",
      "Explain VC dimension with suitable examples.",
      "Discuss PAC learning framework in detail.",
      "Explain hypothesis space and inductive bias with examples.",
      "Explain generalization and overfitting in Machine Learning.",
      "Explain bias–variance trade-off with diagram and examples.",
      "Derive linear regression using least squares method.",
      "Explain single variable and multiple variable linear regression.",
      "Explain Bayesian linear regression model.",
      "Explain gradient descent algorithm with steps and formula.",
      "Explain logistic regression with mathematical model.",
      "Explain perceptron learning algorithm with example.",
      "Explain discriminant function for classification.",
      "Explain Naive Bayes classifier with example.",
      "Explain Support Vector Machine and maximum margin classifier.",
      "Explain decision tree algorithm with advantages and limitations.",
      "Explain Random Forest algorithm and its working.",
      "Explain model combination schemes in ensemble learning.",
      "Explain voting methods in ensemble techniques.",
      "Explain bagging technique with example.",
      "Explain boosting technique and its advantages.",
      "Explain stacking method in ensemble learning.",
      "Explain K-means clustering algorithm with steps and diagram.",
      "Explain KNN algorithm with working and limitations.",
      "Explain instance-based learning in detail.",
      "Explain Gaussian Mixture Model with mathematical concept.",
      "Explain Expectation Maximization algorithm step by step.",
      "Explain Multilayer Perceptron architecture and working.",
      "Explain different activation functions (Sigmoid, Tanh, ReLU).",
      "Explain gradient descent and stochastic gradient descent in neural networks.",
      "Explain backpropagation algorithm with neat diagram.",
      "Explain vanishing gradient problem and how ReLU solves it.",
      "Explain hyperparameter tuning, batch normalization, regularization, and dropout.",
      "Explain design and analysis of ML experiments."
    ],
    important: [
      "Explain supervised learning: classification and regression with real-world examples.",
      "Describe unsupervised learning: clustering and dimensionality reduction techniques.",
      "Explain the complete ML pipeline: data collection, preprocessing, training, validation, testing.",
      "Discuss overfitting and underfitting: causes, detection, and solutions.",
      "Explain feature engineering: importance, techniques, and selection methods.",
      "Describe different types of features and feature scaling: normalization and standardization.",
      "Explain evaluation metrics for classification: accuracy, precision, recall, F1-score, confusion matrix.",
      "Discuss ROC curve, AUC, and their interpretation in model evaluation.",
      "Explain k-fold cross-validation and stratified cross-validation.",
      "Discuss hyperparameter tuning: grid search, random search, Bayesian optimization.",
      "Explain the curse of dimensionality and its impact on model performance.",
      "Describe Principal Component Analysis (PCA) and applications in dimensionality reduction.",
      "Explain different loss functions: MSE, MAE, cross-entropy, hinge loss.",
      "Discuss regularization techniques: L1 (Lasso), L2 (Ridge), Elastic Net, early stopping.",
      "Explain batch normalization: benefits, mechanism, and usage in neural networks.",
      "Describe optimization algorithms: SGD, Momentum, Adam, RMSprop with comparisons.",
      "Explain Convolutional Neural Networks (CNN): architecture, layers, and applications.",
      "Describe Recurrent Neural Networks (RNN): LSTM, GRU, and sequence modeling.",
      "Discuss transfer learning and fine-tuning in deep learning applications.",
      "Explain ensemble methods: voting, stacking, boosting, and bagging in detail."
    ]
  }
};
